print("This is just a test for us to know how the thing works")
print("Again!!!!")
print("This is just a test for us to know how the thing works")
print("Again!!!!")
print("This is just a test for us to know how the thing works")
print("Again!!!!")
print("This is just a test for us to know how the thing works")
print("Again!!!!")